import type {
  BitProfile,
  BitType,
  Machine,
  Material,
  MaterialCategory,
  Operation,
  OperationProfile,
} from "./types";

export const MACHINES: Machine[] = [
  {
    id: "xcarve-pro",
    name: "X-Carve Pro",
    shortName: "Pro",
    blurb: "2 HP air-cooled VFD spindle, 8–24k RPM, ball screws. Most capable factory X-Carve.",
    spindleKind: "vfd",
    spindleName: "2 HP VFD spindle",
    powerHp: 2,
    rpmMin: 8000,
    rpmMax: 24000,
    collet: "ER16",
    maxFeedIpm: 300,
    maxPlungeIpm: 100,
    docCap: 1,
    rigidity: 1,
  },
  {
    id: "xcarve-spindle",
    name: "X-Carve + spindle",
    shortName: "Spindle",
    blurb: "Classic belt-drive X-Carve with an aftermarket VFD spindle. RPM control is good; the frame is not a Pro.",
    spindleKind: "vfd",
    spindleName: "Aftermarket VFD spindle",
    powerHp: 1.5,
    rpmMin: 8000,
    rpmMax: 24000,
    collet: "ER11",
    maxFeedIpm: 140,
    maxPlungeIpm: 19,
    docCap: 0.5,
    rigidity: 0.62,
  },
  {
    id: "xcarve",
    name: "X-Carve",
    shortName: "Classic",
    blurb: "Belt-drive X-Carve with DeWalt DWP611 trim router. Treat the router like a spindle: pick a dial, then set feed from chipload.",
    spindleKind: "router",
    spindleName: "DeWalt DWP611",
    powerHp: 1.25,
    rpmMin: 16000,
    rpmMax: 27000,
    collet: "1/4 in collet",
    maxFeedIpm: 120,
    maxPlungeIpm: 19,
    docCap: 0.5,
    rigidity: 0.55,
    dials: [
      { n: 1, rpm: 16000 },
      { n: 2, rpm: 18200 },
      { n: 3, rpm: 20400 },
      { n: 4, rpm: 22600 },
      { n: 5, rpm: 24800 },
      { n: 6, rpm: 27000 },
    ],
  },
];

export const MATERIALS: Material[] = [
  {
    id: "pine",
    name: "Pine / cedar",
    aka: "Fir, spruce, basswood",
    category: "wood",
    chipload025: 0.006,
    sfm: 1400,
    docFrac: 1,
    plungeFrac: 0.45,
    stepoverRough: 0.45,
    stepoverFinish: 0.15,
    suggestedBit: "upcut",
    suggestedFlutes: 2,
    difficulty: "easy",
    coolant: "Dust collection",
    tips: [
      "Softwoods are forgiving — if the surface fuzzes, switch to a downcut or take a light finish pass.",
      "Pine resins can load flutes. Retract and brush the bit if chips turn gummy.",
      "Climb-cut the final contour if tear-out shows on the exit edge.",
    ],
    warnings: [],
  },
  {
    id: "poplar",
    name: "Poplar",
    aka: "Paint-grade hardwood",
    category: "wood",
    chipload025: 0.0055,
    sfm: 1200,
    docFrac: 0.9,
    plungeFrac: 0.42,
    stepoverRough: 0.42,
    stepoverFinish: 0.12,
    suggestedBit: "upcut",
    suggestedFlutes: 2,
    difficulty: "easy",
    coolant: "Dust collection",
    tips: [
      "Poplar machines like a soft hardwood. Great for prototypes and painted parts.",
      "Green streaks are mineral, not a feeds problem — they cut the same as the rest of the board.",
    ],
    warnings: [],
  },
  {
    id: "maple",
    name: "Maple",
    aka: "Hard / sugar maple",
    category: "wood",
    chipload025: 0.0045,
    sfm: 1000,
    docFrac: 0.8,
    plungeFrac: 0.4,
    stepoverRough: 0.4,
    stepoverFinish: 0.1,
    suggestedBit: "upcut",
    suggestedFlutes: 2,
    difficulty: "moderate",
    coolant: "Dust collection",
    tips: [
      "Hard maple is the default X-Carve hardwood. Start balanced; only go aggressive on a Pro.",
      "A compression bit keeps both faces clean on through-cuts.",
      "If the cut sounds like a scream, you are rubbing — raise feed, do not drop it.",
    ],
    warnings: [],
  },
  {
    id: "oak",
    name: "Oak",
    aka: "Red or white oak",
    category: "wood",
    chipload025: 0.004,
    sfm: 900,
    docFrac: 0.7,
    plungeFrac: 0.35,
    stepoverRough: 0.38,
    stepoverFinish: 0.1,
    suggestedBit: "upcut",
    suggestedFlutes: 2,
    difficulty: "moderate",
    coolant: "Dust collection",
    tips: [
      "Oak is open-grained and abrasive. Carbide dulls faster than in maple — inspect the edge often.",
      "White oak is denser; if the gantry rattles, drop depth per pass before touching feed.",
      "A downcut or compression bit reduces fuzzy grain on the top face.",
    ],
    warnings: ["Abrasive — expect shorter bit life than maple or walnut."],
  },
  {
    id: "walnut",
    name: "Walnut",
    aka: "Black walnut",
    category: "wood",
    chipload025: 0.0045,
    sfm: 1000,
    docFrac: 0.8,
    plungeFrac: 0.4,
    stepoverRough: 0.4,
    stepoverFinish: 0.1,
    suggestedBit: "upcut",
    suggestedFlutes: 2,
    difficulty: "moderate",
    coolant: "Dust collection",
    tips: [
      "Walnut signs and trays are a classic X-Carve job. V-carve lettering, then profile the outline.",
      "The dust is dark and fine — run collection or it packs flutes and burns.",
      "For inlay, leave 0.005–0.010 in of extra depth on the pocket and sneak up on fit.",
    ],
    warnings: [],
  },
  {
    id: "cherry",
    name: "Cherry",
    aka: "Black cherry",
    category: "wood",
    chipload025: 0.0045,
    sfm: 1050,
    docFrac: 0.8,
    plungeFrac: 0.4,
    stepoverRough: 0.4,
    stepoverFinish: 0.1,
    suggestedBit: "downcut",
    suggestedFlutes: 2,
    difficulty: "moderate",
    coolant: "Dust collection",
    tips: [
      "Cherry burns if you linger. Keep feed up and avoid dwelling in corners.",
      "A downcut keeps the show face crisp on signs and plaques.",
    ],
    warnings: ["Scorches easily on slow finish passes — do not drop feed to “be safe.”"],
  },
  {
    id: "bamboo",
    name: "Bamboo",
    aka: "Strand-woven bamboo",
    category: "wood",
    chipload025: 0.0035,
    sfm: 800,
    docFrac: 0.55,
    plungeFrac: 0.32,
    stepoverRough: 0.35,
    stepoverFinish: 0.1,
    suggestedBit: "compression",
    suggestedFlutes: 2,
    difficulty: "demanding",
    coolant: "Dust collection",
    tips: [
      "Treat strand bamboo like a hard, abrasive hardwood. Shallow passes, sharp carbide.",
      "Compression bits reduce chip-out on the laminated faces of cutting boards.",
    ],
    warnings: ["Hard on bits. Replace at the first hint of burning."],
  },
  {
    id: "baltic-birch",
    name: "Baltic birch",
    aka: "Latvian / Finnish birch ply",
    category: "sheet",
    chipload025: 0.0045,
    sfm: 1100,
    docFrac: 0.8,
    plungeFrac: 0.4,
    stepoverRough: 0.4,
    stepoverFinish: 0.12,
    suggestedBit: "compression",
    suggestedFlutes: 2,
    difficulty: "easy",
    coolant: "Dust collection",
    tips: [
      "Compression bits are the default for boxes and cabinets — clean top and bottom.",
      "Glue lines are harder than the veneer. If the bit chatters on a layer, it is dull.",
      "For finger joints, a downcut on the show face plus a light leftover pass beats one deep slot.",
    ],
    warnings: [],
  },
  {
    id: "plywood",
    name: "Plywood",
    aka: "Cabinet or construction ply",
    category: "sheet",
    chipload025: 0.0045,
    sfm: 1050,
    docFrac: 0.7,
    plungeFrac: 0.38,
    stepoverRough: 0.4,
    stepoverFinish: 0.12,
    suggestedBit: "compression",
    suggestedFlutes: 2,
    difficulty: "moderate",
    coolant: "Dust collection",
    tips: [
      "Voids and patches surprise the bit. Keep DOC conservative on cheap sheathing.",
      "Melamine-faced ply wants a compression or downcut to stop chip-out on the plastic face.",
    ],
    warnings: ["Construction plywood can hide voids — clamp well and do not max DOC."],
  },
  {
    id: "mdf",
    name: "MDF",
    aka: "Medium-density fiberboard",
    category: "sheet",
    chipload025: 0.0055,
    sfm: 1300,
    docFrac: 0.9,
    plungeFrac: 0.45,
    stepoverRough: 0.45,
    stepoverFinish: 0.15,
    suggestedBit: "upcut",
    suggestedFlutes: 2,
    difficulty: "easy",
    coolant: "Dust collection — fine dust",
    tips: [
      "MDF is consistent and dusty. An upcut evacuates fibers; wear a respirator even with collection.",
      "Excellent for templates and signs. V-bits stay sharp longer than in hardwood.",
      "Paint-grade edges fuzz if the bit is dull — replace sooner than you think.",
    ],
    warnings: ["The dust is nasty. Collection plus a mask is not optional."],
  },
  {
    id: "melamine",
    name: "Melamine",
    aka: "Particle board with plastic faces",
    category: "sheet",
    chipload025: 0.004,
    sfm: 1000,
    docFrac: 0.6,
    plungeFrac: 0.35,
    stepoverRough: 0.38,
    stepoverFinish: 0.12,
    suggestedBit: "compression",
    suggestedFlutes: 2,
    difficulty: "moderate",
    coolant: "Dust collection",
    tips: [
      "Compression or downcut only — upcuts explode the top laminate.",
      "Score the face with a shallow first pass if you only have an upcut.",
    ],
    warnings: ["Chip-out on the face is the failure mode. Bit geometry matters more than feed."],
  },
  {
    id: "acrylic-cast",
    name: "Cast acrylic",
    aka: "Plexiglas, cell-cast",
    category: "plastic",
    chipload025: 0.004,
    sfm: 800,
    docFrac: 0.45,
    plungeFrac: 0.32,
    stepoverRough: 0.35,
    stepoverFinish: 0.12,
    suggestedBit: "oflute",
    suggestedFlutes: 1,
    difficulty: "moderate",
    coolant: "Air blast, no oil",
    tips: [
      "Single-flute O-flute bits are the right tool. Two flutes trap heat and melt the kerf.",
      "If the edge frosts or the chip welds to the bit, drop RPM and raise feed — heat is the enemy.",
      "Cast acrylic chips into flakes. Extruded strings. If you see strings, you have the wrong sheet or too much heat.",
      "Leave a 0.01 in onion skin and finish the tab with a knife for optical edges.",
    ],
    warnings: ["Melting means the feed is too slow or the RPM is too high. Do not slow down."],
  },
  {
    id: "acrylic-ext",
    name: "Extruded acrylic",
    aka: "Cheaper plexi sheet",
    category: "plastic",
    chipload025: 0.0032,
    sfm: 650,
    docFrac: 0.35,
    plungeFrac: 0.28,
    stepoverRough: 0.32,
    stepoverFinish: 0.1,
    suggestedBit: "oflute",
    suggestedFlutes: 1,
    difficulty: "demanding",
    coolant: "Air blast",
    tips: [
      "Extruded melts much easier than cast. Lower RPM, higher feed, shallow DOC.",
      "Prefer cast for any part where the edge will show.",
    ],
    warnings: ["Gums up flutes quickly. Retract often and keep an air blast on the cut."],
  },
  {
    id: "hdpe",
    name: "HDPE",
    aka: "Cutting-board plastic, Starboard",
    category: "plastic",
    chipload025: 0.006,
    sfm: 900,
    docFrac: 0.7,
    plungeFrac: 0.4,
    stepoverRough: 0.4,
    stepoverFinish: 0.15,
    suggestedBit: "oflute",
    suggestedFlutes: 1,
    difficulty: "easy",
    coolant: "Air blast",
    tips: [
      "HDPE cuts like cold butter with a single flute. Chips should be curly ribbons, not dust.",
      "Clamp aggressively — the sheet wants to lift. Tabs on through-cuts are mandatory.",
      "A slightly higher feed beats a polished look; rubbing makes a smeared, shiny weld.",
    ],
    warnings: [],
  },
  {
    id: "delrin",
    name: "Delrin / acetal",
    aka: "POM, acetal copolymer",
    category: "plastic",
    chipload025: 0.004,
    sfm: 750,
    docFrac: 0.5,
    plungeFrac: 0.32,
    stepoverRough: 0.35,
    stepoverFinish: 0.1,
    suggestedBit: "oflute",
    suggestedFlutes: 1,
    difficulty: "moderate",
    coolant: "Air blast",
    tips: [
      "Delrin holds dimension. Use it for jigs, gears, and bushings on the Pro.",
      "Sharp O-flute, moderate DOC. The chips should be pale and dry, not melted blobs.",
    ],
    warnings: [],
  },
  {
    id: "polycarbonate",
    name: "Polycarbonate",
    aka: "Lexan",
    category: "plastic",
    chipload025: 0.003,
    sfm: 600,
    docFrac: 0.3,
    plungeFrac: 0.28,
    stepoverRough: 0.3,
    stepoverFinish: 0.1,
    suggestedBit: "oflute",
    suggestedFlutes: 1,
    difficulty: "demanding",
    coolant: "Air blast",
    tips: [
      "PC is gummy. Single flute, low RPM, high feed, tiny DOC.",
      "Do not use coolant that crazes polycarbonate. Air only.",
    ],
    warnings: ["Melts and grabs. If the bit loads, stop and clear — do not push through."],
  },
  {
    id: "sintra",
    name: "PVC / Sintra",
    aka: "Foamed PVC, Komatex",
    category: "plastic",
    chipload025: 0.005,
    sfm: 900,
    docFrac: 0.7,
    plungeFrac: 0.4,
    stepoverRough: 0.4,
    stepoverFinish: 0.15,
    suggestedBit: "oflute",
    suggestedFlutes: 1,
    difficulty: "easy",
    coolant: "Dust collection — chlorine dust",
    tips: [
      "Foamed PVC is a sign-shop staple. Single flute, plenty of feed, light DOC on dense grades.",
      "Do not laser this later — CNC only. Collect the dust; it is chlorinated.",
    ],
    warnings: ["Do not overheat. Burning PVC fumes are toxic."],
  },
  {
    id: "abs",
    name: "ABS",
    aka: "Sheet or printed stock",
    category: "plastic",
    chipload025: 0.0045,
    sfm: 800,
    docFrac: 0.5,
    plungeFrac: 0.35,
    stepoverRough: 0.38,
    stepoverFinish: 0.12,
    suggestedBit: "oflute",
    suggestedFlutes: 1,
    difficulty: "moderate",
    coolant: "Air blast",
    tips: [
      "ABS machines cleanly with an O-flute. Watch heat — it will smear and re-weld.",
      "Support thin sheet; it flexes more than acrylic.",
    ],
    warnings: [],
  },
  {
    id: "aluminum-6061",
    name: "Aluminum 6061",
    aka: "The hobby-CNC alloy",
    category: "metal",
    chipload025: 0.002,
    sfm: 800,
    docFrac: 0.1,
    plungeFrac: 0.22,
    stepoverRough: 0.25,
    stepoverFinish: 0.08,
    suggestedBit: "oflute",
    suggestedFlutes: 1,
    difficulty: "demanding",
    coolant: "Wax, WD-40, or mist — never dry",
    tips: [
      "Single-flute carbide made for aluminum. Two flutes pack chips and weld.",
      "Flood the cut with wax stick or a drop of cutting fluid every pass. Dry aluminum galls instantly.",
      "Shallow DOC, real chipload, air blast to clear chips. Dust is a failure; curly chips are success.",
      "On a classic X-Carve, keep DOC tiny and feed modest. The Pro can take a real cut.",
      "Climb milling plus a rigid hold-down (not just tape) keeps the plate from singing.",
    ],
    warnings: [
      "Lubricant is required. A dry cut will weld chips to the bit and snap it.",
      "Classic belt-drive X-Carve is marginal in aluminum — prefer the Pro.",
    ],
  },
  {
    id: "aluminum-5052",
    name: "Aluminum 5052",
    aka: "Softer sheet aluminum",
    category: "metal",
    chipload025: 0.0022,
    sfm: 700,
    docFrac: 0.1,
    plungeFrac: 0.22,
    stepoverRough: 0.25,
    stepoverFinish: 0.08,
    suggestedBit: "oflute",
    suggestedFlutes: 1,
    difficulty: "demanding",
    coolant: "Wax or mist",
    tips: [
      "5052 is gummier than 6061. Lower RPM a notch and keep lubricant wet on the bit.",
      "Same rules as 6061: 1-flute, shallow, never dry.",
    ],
    warnings: ["Softer grades weld even faster. Do not skip lubricant."],
  },
  {
    id: "brass",
    name: "Brass",
    aka: "360 or sheet brass",
    category: "metal",
    chipload025: 0.0015,
    sfm: 500,
    docFrac: 0.08,
    plungeFrac: 0.2,
    stepoverRough: 0.22,
    stepoverFinish: 0.08,
    suggestedBit: "oflute",
    suggestedFlutes: 1,
    difficulty: "demanding",
    coolant: "Wax or cutting fluid",
    tips: [
      "Brass is doable on the Pro with tiny DOC and a sharp 1-flute. Not a first metal job.",
      "360 free-machining brass is kinder than cartridge brass.",
    ],
    warnings: ["Skip brass on a belt-drive X-Carve. Even the Pro wants conservative DOC."],
  },
  {
    id: "xps",
    name: "XPS foam",
    aka: "Pink / blue insulation foam",
    category: "foam",
    chipload025: 0.01,
    sfm: 1600,
    docFrac: 1.4,
    plungeFrac: 0.55,
    stepoverRough: 0.5,
    stepoverFinish: 0.2,
    suggestedBit: "upcut",
    suggestedFlutes: 2,
    difficulty: "easy",
    coolant: "Vacuum — static dust",
    tips: [
      "Foam wants speed. High feed, deep DOC, sharp bit. Slow cuts melt the kerf.",
      "A cheap 1/4 in upcut is fine. Save Spektra bits for hardwood.",
    ],
    warnings: [],
  },
  {
    id: "hdu",
    name: "HDU sign foam",
    aka: "High-density urethane, Precision Board",
    category: "foam",
    chipload025: 0.007,
    sfm: 1400,
    docFrac: 1,
    plungeFrac: 0.45,
    stepoverRough: 0.45,
    stepoverFinish: 0.12,
    suggestedBit: "ball",
    suggestedFlutes: 2,
    difficulty: "easy",
    coolant: "Dust collection",
    tips: [
      "HDU is what sign shops 3D-carve. Ball nose for finish, flat for roughing.",
      "Density (lb/ft³) changes the cut — 15 lb machines like MDF, 30 lb like a soft hardwood.",
    ],
    warnings: [],
  },
  {
    id: "corian",
    name: "Corian",
    aka: "Solid surface, acrylic resin",
    category: "other",
    chipload025: 0.003,
    sfm: 700,
    docFrac: 0.35,
    plungeFrac: 0.28,
    stepoverRough: 0.3,
    stepoverFinish: 0.1,
    suggestedBit: "upcut",
    suggestedFlutes: 2,
    difficulty: "demanding",
    coolant: "Dust collection + light air",
    tips: [
      "Solid surface is abrasive. Use carbide, shallow DOC, and expect to dress the bit.",
      "Good for templates and jigs that have to live in a wet shop.",
    ],
    warnings: ["Abrasive filler. Do not use a wood bit you care about."],
  },
  {
    id: "g10",
    name: "G10 / carbon fiber",
    aka: "FR4, CFRP sheet",
    category: "other",
    chipload025: 0.002,
    sfm: 500,
    docFrac: 0.25,
    plungeFrac: 0.25,
    stepoverRough: 0.28,
    stepoverFinish: 0.1,
    suggestedBit: "downcut",
    suggestedFlutes: 2,
    difficulty: "demanding",
    coolant: "HEPA collection — fibers",
    tips: [
      "Diamond or dedicated composite bits. Wood end mills die in one job.",
      "Downcut or compression to keep fibers from fuzzing the top.",
      "Respirator and sealed collection. Carbon and glass dust is not shop-vac dust.",
    ],
    warnings: [
      "Hazardous dust. Do not cut without filtration.",
      "Abrasive — standard carbide geometry will not last.",
    ],
  },
];

export const BITS: BitProfile[] = [
  {
    id: "upcut",
    name: "Spiral upcut",
    blurb: "Pulls chips up. Best evacuation, fuzzes the top face.",
    chipload: 1,
    doc: 1,
    plunge: 1,
    defaultDiameterIn: 0.25,
  },
  {
    id: "downcut",
    name: "Spiral downcut",
    blurb: "Pushes chips down. Clean top, poorer evacuation — take shallower passes.",
    chipload: 0.85,
    doc: 0.75,
    plunge: 0.85,
    defaultDiameterIn: 0.25,
  },
  {
    id: "compression",
    name: "Compression",
    blurb: "Up + down flutes. Clean both faces of plywood and laminate.",
    chipload: 0.95,
    doc: 0.9,
    plunge: 0.9,
    defaultDiameterIn: 0.25,
  },
  {
    id: "ball",
    name: "Ball nose",
    blurb: "3D carving and finish passes. Reduce chipload; use a small stepover.",
    chipload: 0.82,
    doc: 0.7,
    plunge: 0.9,
    defaultDiameterIn: 0.125,
  },
  {
    id: "vbit60",
    name: "V-bit 60°",
    blurb: "Fine lettering and deep V-carves. Feed is limited by the tiny tip.",
    chipload: 0.45,
    doc: 0.55,
    plunge: 0.7,
    forceFlutes: 2,
    defaultDiameterIn: 0.5,
  },
  {
    id: "vbit90",
    name: "V-bit 90°",
    blurb: "Standard sign lettering. Wider groove than 60°, a bit more feed.",
    chipload: 0.55,
    doc: 0.65,
    plunge: 0.75,
    forceFlutes: 2,
    defaultDiameterIn: 0.5,
  },
  {
    id: "oflute",
    name: "O-flute / 1-flute",
    blurb: "Plastics and aluminum. One big flute clears chips and heat.",
    chipload: 1.15,
    doc: 1,
    plunge: 1,
    forceFlutes: 1,
    defaultDiameterIn: 0.125,
  },
  {
    id: "surfacing",
    name: "Surfacing",
    blurb: "Spoilboard and slab flattening. Shallow DOC, wide stepover, lower RPM.",
    chipload: 0.78,
    doc: 0.22,
    plunge: 0.6,
    defaultDiameterIn: 1,
  },
];

export const OPERATIONS: OperationProfile[] = [
  {
    id: "profile",
    name: "Profile",
    blurb: "Cut-out and contour. Full chipload, slots need good evacuation.",
    chipload: 1,
    doc: 1,
    stepover: "none",
  },
  {
    id: "pocket",
    name: "Pocket",
    blurb: "Area clearance. Slightly less chipload so chips can escape the pocket.",
    chipload: 0.88,
    doc: 0.9,
    stepover: "rough",
  },
  {
    id: "vcarve",
    name: "V-carve",
    blurb: "Lettering and decorative grooves. Tip-limited feed.",
    chipload: 0.7,
    doc: 0.85,
    stepover: "none",
  },
  {
    id: "3d-rough",
    name: "3D rough",
    blurb: "Bulk removal before a finish pass. Leave stock; keep stepover wide.",
    chipload: 0.9,
    doc: 0.95,
    stepover: "rough",
  },
  {
    id: "3d-finish",
    name: "3D finish",
    blurb: "Light DOC, small stepover, reduced chipload for surface quality.",
    chipload: 0.55,
    doc: 0.35,
    stepover: "finish",
  },
  {
    id: "surfacing",
    name: "Surfacing",
    blurb: "Flatten a slab or spoilboard in thin, wide passes.",
    chipload: 0.8,
    doc: 0.25,
    stepover: "rough",
  },
  {
    id: "drill",
    name: "Drill / peck",
    blurb: "Plunge only. Peck to clear chips; XY feed is unused.",
    chipload: 0.4,
    doc: 0.5,
    stepover: "none",
  },
];

export const CATEGORIES: { id: MaterialCategory; label: string }[] = [
  { id: "wood", label: "Wood" },
  { id: "sheet", label: "Sheet" },
  { id: "plastic", label: "Plastic" },
  { id: "metal", label: "Metal" },
  { id: "foam", label: "Foam" },
  { id: "other", label: "Other" },
];

export const DIAMETERS_IN = [0.0625, 0.125, 0.1875, 0.25, 0.375, 0.5, 0.75, 1, 1.25];
export const DIAMETERS_MM = [1, 2, 3, 3.175, 4, 6, 6.35, 8, 10, 12, 12.7, 16, 19, 25.4, 32];

export const PROJECTS: {
  id: string;
  label: string;
  materialId: string;
  bitType: BitType;
  diameterIn: number;
  flutes: number;
  operation: Operation;
}[] = [
  {
    id: "walnut-sign",
    label: "Walnut sign",
    materialId: "walnut",
    bitType: "vbit90",
    diameterIn: 0.5,
    flutes: 2,
    operation: "vcarve",
  },
  {
    id: "maple-board",
    label: "Maple board",
    materialId: "maple",
    bitType: "surfacing",
    diameterIn: 1,
    flutes: 2,
    operation: "surfacing",
  },
  {
    id: "birch-box",
    label: "Birch box",
    materialId: "baltic-birch",
    bitType: "compression",
    diameterIn: 0.25,
    flutes: 2,
    operation: "profile",
  },
  {
    id: "mdf-template",
    label: "MDF template",
    materialId: "mdf",
    bitType: "upcut",
    diameterIn: 0.25,
    flutes: 2,
    operation: "profile",
  },
  {
    id: "acrylic-panel",
    label: "Acrylic panel",
    materialId: "acrylic-cast",
    bitType: "oflute",
    diameterIn: 0.125,
    flutes: 1,
    operation: "profile",
  },
  {
    id: "alu-plate",
    label: "6061 plate",
    materialId: "aluminum-6061",
    bitType: "oflute",
    diameterIn: 0.125,
    flutes: 1,
    operation: "pocket",
  },
];

export function getMachine(id: string): Machine {
  return MACHINES.find((m) => m.id === id) ?? MACHINES[0];
}

export function getMaterial(id: string): Material {
  return MATERIALS.find((m) => m.id === id) ?? MATERIALS[2];
}

export function getBit(id: BitType): BitProfile {
  return BITS.find((b) => b.id === id) ?? BITS[0];
}

export function getOperation(id: Operation): OperationProfile {
  return OPERATIONS.find((o) => o.id === id) ?? OPERATIONS[0];
}
